### ISSUE TITLE
Version 1.2 is not available

### ISSUE THREAD

**Issue by markoradinovic** [dkorotych/gradle-maven-exec-plugin#10]
Hi, something is wrong with version 1.2. I can't download it from https://plugins.gradle.org/m2/.
Version 1.1 is available.

**Comment by dkorotych** [comment]
Hi, thanks for using the plugin :)
Maybe something is wrong with the site, because I can not open it now and it shows a blank page, the previous version can be cached on the local machine

But in any case, I'll check if the plug-in is available as soon as the site returns to work

**Comment by dkorotych** [comment]
You, really, are right. Version 1.2 does not download from the site.
Thanks

**Comment by dkorotych** [comment]
Fixed in [1.2.1](https://plugins.gradle.org/plugin/com.github.dkorotych.gradle-maven-exec)
