### ISSUE TITLE
'mvn.cmd' error

### ISSUE THREAD

**Issue by ferencz1** [dkorotych/gradle-maven-exec-plugin#16]
Hello,
I found out your plugin and seems it is just what I need for my project but I can't execute my task, error message is:
"'mvn.cmd' is not recognized as an internal or external command,
operable program or batch file."
I'm using gradle 2.8, groovy 2.4.4, java 1.8.0_121.

Thank You

**Comment by dkorotych** [comment]
1. Do you have a maven installed in the system? The plugin only generates a command line for its local launch. If you do not have it installed, then you can use [maven-wrapper]( https://github.com/takari/maven-wrapper)
2. The minimum version of Gradle that is supported by the plugin is 2.13

**Comment by ferencz1** [comment]
Hi,
1. Yes, I have installed maven 3.0.5. I'm using Windows 7 x64 OS and from cmd command "mvn -v" works.

**Comment by rbratten** [comment]
I am having the same problem, Running 1.2.2.1 of the plugin,

`
Gradle 4.8.1
Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_171 (Oracle Corporation 25.171-b11)
OS:           Windows 10 10.0 amd64
Maven home: C:\IDE\apache-maven-3.2.1-bin\apache-maven-3.2.1
Java version: 1.8.0_171, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_171\jre
`

Error:'mvn.cmd' is not recognized as an internal or external command,
operable program or batch file.

**Comment by dkorotych** [comment]
You're right. Maven up to version 3.3.1 does not contain the file mvn.cmd, only mvn.bat. I'll fix it in new plugin version

**Comment by dkorotych** [comment]
Please test new version (2.0)
