### ISSUE TITLE
how to invoke custom maven plugin by this gradle-maven-exec-plugin?

### ISSUE THREAD

**Issue by fgwh** [dkorotych/gradle-maven-exec-plugin#28]
hi ,  I see the useCase.gradle which can invoke maven plugin such as maven-archetype-quickstart,but don't have to configure groupId ,I don't know how to invoke custom maven plugin

**Comment by wtfiwtz** [comment]
Here's an example in `build.gradle`:

```xml
plugins {
    id 'java-library'
    id "com.github.dkorotych.gradle-maven-exec" version "2.2.1"
    id 'maven-publish'
}

task wsimport(type: MavenExec) {
    goals 'generate-sources'
}
```
