### ISSUE TITLE
Failed to apply plugin 'com.github.dkorotych.gradle-maven-exec'.

### ISSUE THREAD

**Issue by venkateshwarlu808** [dkorotych/gradle-maven-exec-plugin#40]
I am facing below issue after upgrading the Gradle to 7.4 version from 6.5 version .

Plugins are not working with latest Gradle is there is any alternative plugin available for the same .

This is the wavemaker application ,Below is is my configuration in build.gradle file .
 
build.gradle file :

apply plugin: 'maven-publish'
apply plugin: "com.github.dkorotych.gradle-maven-exec"

version = '1.0.0'

buildscript {
  dependencies {
    classpath "gradle.plugin.com.github.dkorotych.gradle.maven.exec:gradle-maven-exec-plugin:2.1"
  }
}

task invokeMaven(type: MavenExec) {
    goals 'install'
    options {
        activateProfiles = ['xxxxxxx']
    }
}

**Comment by venkateshwarlu808** [comment]
> I use gradle 7.4.2 and faced this issue too

Do u find any resolution ?.
If please share with me .

**Comment by yasamprom** [comment]
> > I use gradle 7.4.2 and faced this issue too
> 
> Do u find any resolution ?. If please share with me .
It seems plugin is outdated. I didn't find solution how to use it with gradle 7.4.2
Finally, I just added pom.xml in my [project](https://github.com/objectionary/eo-intellij-plugin) and combined both build systems

**Comment by dkorotych** [comment]
Try to use version 3.0
